# Generated by Django 5.2.6 on 2025-09-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250, verbose_name='Источник')),
                ('text', models.TextField(unique=True, verbose_name='Цитата')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Вес')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Цитату',
                'verbose_name_plural': 'Цитаты',
                'db_table': 'citation',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Счетчик')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.GenericIPAddressField(verbose_name='IP пользователя')),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.citation', verbose_name='Цитата')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.GenericIPAddressField(verbose_name='IP пользователя')),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.citation', verbose_name='Цитата')),
            ],
        ),
    ]
