# Generated by Django 5.2.6 on 2025-09-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
    ]
